- name: Check service definition file
  stat: path="/lib/systemd/system/romanescU_api.service"
  register: api_service

- name: Generate service definition file
  template:
    src: "./templates/romanescu_api.service.j2"
    dest: "/lib/systemd/system/romanescU_api.service"
  when: not api_service.stat.exists
  become: yes

- name: Start and enable service
  service:
    name: "romanescU_api"
    state: "started"
    enabled: yes
  become: yes

- name: Check service definition file
  stat: path="/lib/systemd/system/romanescU_www.service"
  register: www_service

- name: Generate service definition file
  template:
    src: "./templates/romanescu_www.service.j2"
    dest: "/lib/systemd/system/romanescU_www.service"
  when: not www_service.stat.exists
  become: yes

- name: Start and enable service
  service:
    name: "romanescU_www"
    state: "started"
    enabled: yes
  become: yes
