- name: Clone romanescU-spring-api project
  git:
    repo: "https://github.com/gov-ithub/romanescU-spring-api.git"
    dest: "{{ spring_api_folder }}"
    force: yes

- name: Build romanescU-spring-api
  shell: "/usr/bin/mvn clean package"
  args:
    chdir: "{{ spring_api_folder }}"

- name: Check service definition file
  stat: path="/lib/systemd/system/romanescU_api.service"
  register: api_service

- name: Generate service definition file
  template:
    src: "./templates/romanescu_api.service.j2"
    dest: "/lib/systemd/system/romanescU_api.service"
#  when: not api_service.stat.exists
  become: yes

- name: Start and enable service
  service:
    name: "romanescU_api"
    state: "started"
    enabled: yes
  become: yes
