- name: Clone romanescU-spring-api project
  git:
    repo: "https://github.com/gov-ithub/romanescU-spring-api.git"
    dest: "/tmp/romanescU-spring-api"
    force: yes

- name: Build romanescU-spring-api
  shell: "/usr/bin/mvn clean package"
  args:
    chdir: "/tmp/romanescU-spring-api"